version: '3'

services:
  newbie-2019:
    image: ${IMAGE_TAG}:latest
    networks:
    - traefik_net
    - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
      - "traefik.tags=http"
      - "traefik.port=5000"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_net"
      - "traefik.backend=newbie-2019"
      - "traefik.frontend.rule=Host:newbie2019.zjuqsc.com"
networks:
  traefik_net:
    external: true
